version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.5.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # working_directory: ~/repo
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
      - ~/.cache/yarn

    steps:
      - checkout
      - run yarn
      
      # # Download and cache dependencies
      # - restore_cache:
          # keys:
          # - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          # - v1-dependencies-

      # - run: yarn install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test